adding scacap/action-surefire-report@v1

diff --git a/.github/workflows/mvn-tests.yml b/.github/workflows/mvn-tests.yml
--- a/.github/workflows/mvn-tests.yml
+++ b/.github/workflows/mvn-tests.yml
@@ -55,7 +55,11 @@ jobs:
 
       # Install dependencies and run Maven tests
       - name: Run Maven Tests
-        run: mvn test
+        run: mvn test --batch-mode --fail-at-end
+      
+      - name: Publish Test Report
+        if: success() || failure()
+        uses: scacap/action-surefire-report@v1
 
       # Upload Surefire reports including .xml, .html, .css, and screenshots
       - name: Upload Surefire Reports and Artifacts
@@ -64,73 +68,73 @@ jobs:
           name: surefire-reports
           path: target/surefire-reports/*
 
-  display-surefire-reports:
-    runs-on: ubuntu-latest
-    needs: test
-    if: always()  # Ensure this job runs regardless of previous job success or failure
+  # display-surefire-reports:
+  #   runs-on: ubuntu-latest
+  #   needs: test
+  #   if: always()  # Ensure this job runs regardless of previous job success or failure
 
-    steps:
-      # Download Surefire reports
-      - name: Download Surefire reports
-        uses: actions/download-artifact@v3
-        with:
-          name: surefire-reports
+  #   steps:
+  #     # Download Surefire reports
+  #     - name: Download Surefire reports
+  #       uses: actions/download-artifact@v3
+  #       with:
+  #         name: surefire-reports
       
-            # Show Surefire reports
-      - name: LS
-        run: |
-          echo "Displaying Surefire reports:"
-          ls -R /home/runner/work/selenium-java/selenium-java
+  #           # Show Surefire reports
+  #     - name: LS
+  #       run: |
+  #         echo "Displaying Surefire reports:"
+  #         ls -R /home/runner/work/selenium-java/selenium-java
 
 
-      # # Move surefire-reports to the target folder
-      # - name: Move Surefire reports to target folder
-      #   run: |
-      #     echo "Moving Surefire reports to target folder..."
-      #     mkdir -p target/surefire-reports
-      #     mv surefire-reports/* target/surefire-reports/
+  #     # # Move surefire-reports to the target folder
+  #     # - name: Move Surefire reports to target folder
+  #     #   run: |
+  #     #     echo "Moving Surefire reports to target folder..."
+  #     #     mkdir -p target/surefire-reports
+  #     #     mv surefire-reports/* target/surefire-reports/
 
-      # # Show Surefire reports
-      # - name: Show Surefire reports
-      #   run: |
-      #     echo "Displaying Surefire reports:"
-      #     ls -R target/surefire-reports
+  #     # # Show Surefire reports
+  #     # - name: Show Surefire reports
+  #     #   run: |
+  #     #     echo "Displaying Surefire reports:"
+  #     #     ls -R target/surefire-reports
 
-      # Display HTML Report (if available)
-      - name: Display HTML Report (if available)
-        run: cat /home/runner/work/selenium-java/selenium-java/index.html
+  #     # Display HTML Report (if available)
+  #     - name: Display HTML Report (if available)
+  #       run: cat /home/runner/work/selenium-java/selenium-java/index.html
   
-      #   # Publish Surefire reports to GitHub Pages
-      # - name: Deploy HTML report to GitHub Pages
-      #   uses: peaceiris/actions-gh-pages@v3
-      #   with:
-      #     github_token: ${{ secrets.GITHUB_TOKEN }}
-      #     publish_dir: /home/runner/work/selenium-java/selenium-java/
+  #     #   # Publish Surefire reports to GitHub Pages
+  #     # - name: Deploy HTML report to GitHub Pages
+  #     #   uses: peaceiris/actions-gh-pages@v3
+  #     #   with:
+  #     #     github_token: ${{ secrets.GITHUB_TOKEN }}
+  #     #     publish_dir: /home/runner/work/selenium-java/selenium-java/
 
-  push_to_gh_pages:
-    runs-on: ubuntu-latest
-    needs: test
-    if: always()  # Ensure this job runs regardless of previous job success or failure
+  # push_to_gh_pages:
+  #   runs-on: ubuntu-latest
+  #   needs: test
+  #   if: always()  # Ensure this job runs regardless of previous job success or failure
   
-    steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
+  #   steps:
+  #     - name: Checkout code
+  #       uses: actions/checkout@v2
 
-      # Set up Git config
-      - name: Set up Git config
-        run: |
-          git config user.name "github-actions"
-          git config user.email "github-actions@github.com"
+  #     # Set up Git config
+  #     - name: Set up Git config
+  #       run: |
+  #         git config user.name "github-actions"
+  #         git config user.email "github-actions@github.com"
 
-      # Create a commit (example)
-      - name: Create a commit
-        run: |
-          echo "Changes made" > changes.txt
-          git add changes.txt
-          git commit -m "Add changes"
+  #     # Create a commit (example)
+  #     - name: Create a commit
+  #       run: |
+  #         echo "Changes made" > changes.txt
+  #         git add changes.txt
+  #         git commit -m "Add changes"
 
-      # Push the commit or tag to the gh-pages branch
-      - name: Push changes to gh-pages
-        run: |
-          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/techslateramu/selenium-java.git
-          git push origin gh-pages
+  #     # Push the commit or tag to the gh-pages branch
+  #     - name: Push changes to gh-pages
+  #       run: |
+  #         git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/techslateramu/selenium-java.git
+  #         git push origin gh-pages
